version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - 3002:5432
    volumes: 
      - db:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    image: dgacitua/backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3001:4000
  frontend:
    build:
      context: ./frontend
    image: dgacitua/frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
volumes:
  db:
    driver: local